### GET Token
GET {{host}}/auth/customer/emailpass
Content-Type: application/json

{
    "email": "{{customer.email}}",
    "password": "{{customer.password}}"
}

###

### GET Measurements
GET {{host}}/measurement/
Content-Type: application/json

{
    "email": "{{customer.email}}",
    "password": "{{customer.password}}"
}

###