### GET Measurements
GET {{host}}/store/measurements
Content-Type: application/json
Authorization: Bearer {{auth_token}}
x-publishable-api-key: {{publishable-api-key}}

{
    "email": "{{customer.email}}",
    "password": "{{customer.password}}"
}

###