### GET Token
GET {{host}}/auth/customer/emailpass
Content-Type: application/json

{
    "email": "{{customer.email}}",
    "password": "{{customer.password}}"
}

> {%
    client.global.set("auth_token", response.body.token);
    client.log("Token stored: " + response.body.token);
%}

###