### GET Measurements
GET {{host}}/store/measurements/01KEPE984WEAYH1TG7JSX7Q1KA/
Content-Type: application/json
Authorization: Bearer {{auth_token}}
x-publishable-api-key: {{publishable-api-key}}

###