### CREATE a Measurements
POST {{host}}/store/measurements
Content-Type: application/json
Authorization: Bearer {{auth_token}}
x-publishable-api-key: {{publishable-api-key}}

{
  "name": "test",
  "forehead": 12,
  "mouth": 12,
  "neck": 12
}

> {%
    client.global.set("measurement_id", response.body.post.id);
    client.log("Measurement ID stored: " + response.body.post.id);
%}

###